<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_land Islands_phoneNumber1_phone_number</name>
   <tag></tag>
   <elementGuidId>f4e44417-3675-469e-8d24-1cd6c7c4319c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phoneNumber1_phone_number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phoneNumber1_phone_number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eda8ce67-bd22-48d7-a116-2a758f3ff179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phoneNumber1_phone_number</value>
      <webElementGuid>099bbd92-c525-43a2-91f0-f568a0b32f83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Contoh: 0856xxxx</value>
      <webElementGuid>2033e204-5166-4092-80f5-1c6324bfb4a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>f69a3196-3aea-4db2-a553-7048ecd36723</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>return event.charCode >= 48 &amp;&amp; event.charCode &lt;= 57</value>
      <webElementGuid>4fc84e8e-1048-4993-be20-bc94ca365b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vue-input-ui__input</value>
      <webElementGuid>9640d1a3-26b1-4530-ad9a-18938e1ad292</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneNumber1_phone_number&quot;)</value>
      <webElementGuid>4e3b284e-9f21-427e-b843-66e7dcc4d0b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phoneNumber1_phone_number']</value>
      <webElementGuid>17b03dde-f2c0-4f84-a975-9a4e8cd31db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form-number']/div/div/div[2]/div/input</value>
      <webElementGuid>2729fd19-9c2c-4570-8ad9-37cbc0be4205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>30d7badb-f0e0-4087-8fc3-71cae48b3473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'phoneNumber1_phone_number' and @placeholder = 'Contoh: 0856xxxx' and @type = 'tel']</value>
      <webElementGuid>a6ce2e6c-db94-4ba5-ae42-f82e5842760a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
