<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tabphonenumber</name>
   <tag></tag>
   <elementGuidId>3953398f-cb9b-4e8f-882d-31ebba858f97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-phone-otp']/div/div/div/div/div/div/div[3]/div/div[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>731b299d-dd9b-4c47-8ce6-7ea5b4b28077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default</value>
      <webElementGuid>01a40fe1-03d2-49cf-903b-fb3cb298eac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nomor Telepon</value>
      <webElementGuid>80e80786-de11-4f69-8bc5-76119c80d964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-phone-otp&quot;)/div[@class=&quot;section p-5&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-12 col-md-12 col-lg-8 offset-lg-2&quot;]/div[@class=&quot;login-wrapper&quot;]/div[@class=&quot;login-container&quot;]/div[3]/div[@class=&quot;d-flex wrapper-tabs&quot;]/div[@class=&quot;w-50 text-center&quot;]/span[@class=&quot;btn btn-default&quot;]</value>
      <webElementGuid>d33a0d19-4232-4463-9cba-c998a3b5bd6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-phone-otp']/div/div/div/div/div/div/div[3]/div/div[2]/span</value>
      <webElementGuid>8b3c4961-3b15-4db5-95b9-42ea7c0c7c3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail'])[1]/following::span[1]</value>
      <webElementGuid>0d3558b0-3e83-477c-a9f8-ec09eb3ba09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar'])[2]/following::span[2]</value>
      <webElementGuid>1c4a69a9-b9b0-4f08-aebd-aea513c62449</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail'])[2]/preceding::span[1]</value>
      <webElementGuid>f3f44675-b19b-4fa9-8cbd-d8c3af83716b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wajib diisi'])[1]/preceding::span[1]</value>
      <webElementGuid>11242d5a-cfc9-45bc-901d-3bda876f3a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nomor Telepon']/parent::*</value>
      <webElementGuid>a65472d3-d7fd-4dc3-bb27-5640355ca512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/span</value>
      <webElementGuid>9332d69a-ba00-49a2-97e1-33d77c198b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Nomor Telepon' or . = 'Nomor Telepon')]</value>
      <webElementGuid>5070472c-bc18-4444-817e-236c2ffde50b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
