<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>countryselector</name>
   <tag></tag>
   <elementGuidId>1d528566-f607-412a-9e92-294de84bd704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.country-selector-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-phone-otp']/div/div/div/div/div/div/span/form/div[3]/div/div/div/div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>7c787aad-623d-4371-8f95-642b0caaaba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>country-selector-arrow</value>
      <webElementGuid>a464d053-f572-47e0-a9f4-66755a499bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
    ▼
  </value>
      <webElementGuid>bf6dacc3-64cf-4d94-adb1-3cdfe44e4809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-phone-otp&quot;)/div[@class=&quot;section p-5&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-12 col-md-12 col-lg-8 offset-lg-2&quot;]/div[@class=&quot;register-wrapper&quot;]/div[@class=&quot;register-container&quot;]/span[1]/form[1]/div[@class=&quot;form-group&quot;]/div[@class=&quot;component&quot;]/div[@class=&quot;vue-phone-number-input flex&quot;]/div[@class=&quot;select-country-container&quot;]/div[@class=&quot;field country-selector input-country-selector is-focused has-value&quot;]/div[@class=&quot;country-selector-arrow&quot;]</value>
      <webElementGuid>5a6300c4-a3fe-45af-a2f0-f653385d9004</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-phone-otp']/div/div/div/div/div/div/span/form/div[3]/div/div/div/div/div[2]</value>
      <webElementGuid>7241d9aa-b0fd-4fab-a522-d4dc79810020</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Telepon'])[1]/following::div[7]</value>
      <webElementGuid>9d596992-b674-4c17-b77e-ece2a6ca0c1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-mail'])[1]/following::div[9]</value>
      <webElementGuid>ed376149-e33e-431b-87d7-a94e96846cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode negara'])[1]/preceding::div[1]</value>
      <webElementGuid>696ca22e-5abb-4be9-8df0-06ec6e0cbed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Afghanistan (‫افغانستان‬‎)'])[1]/preceding::div[3]</value>
      <webElementGuid>346b2291-6d86-48c1-9b4e-c0cdbce63fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='▼']/parent::*</value>
      <webElementGuid>0932a845-aca9-4166-82fa-e84c25b1676f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div[2]</value>
      <webElementGuid>13fb2317-19f5-4944-b605-3c75922abcbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
    ▼
  ' or . = '
    ▼
  ')]</value>
      <webElementGuid>dce28948-c07b-49cd-a821-90a2d3800333</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
