<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Indonesia</name>
   <tag></tag>
   <elementGuidId>fdcd7fcb-76f8-4909-a286-b0cd943bf8b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.flex.align-center.country-list-item.selected.keyboard-selected</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='page-phone-otp']/div/div/div/div/div/div/span/form/div[3]/div/div/div/div/div[3]/div[99]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f87d42b4-878f-4919-a64b-9f711cc736d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex align-center country-list-item selected keyboard-selected</value>
      <webElementGuid>c10fbae0-b903-44e9-a1cb-eea06fcee857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
          Indonesia
        </value>
      <webElementGuid>1512b11a-6f92-4285-adcc-b5fe7e5c881c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-phone-otp&quot;)/div[@class=&quot;section p-5&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-12 col-md-12 col-lg-8 offset-lg-2&quot;]/div[@class=&quot;register-wrapper&quot;]/div[@class=&quot;register-container&quot;]/span[1]/form[1]/div[@class=&quot;form-group&quot;]/div[@class=&quot;component&quot;]/div[@class=&quot;vue-phone-number-input flex&quot;]/div[@class=&quot;select-country-container&quot;]/div[@class=&quot;field country-selector input-country-selector is-focused has-value&quot;]/div[@class=&quot;country-list&quot;]/div[@class=&quot;flex align-center country-list-item selected keyboard-selected&quot;]</value>
      <webElementGuid>99ba8472-6736-4850-a3f8-2b79e3366e3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-phone-otp']/div/div/div/div/div/div/span/form/div[3]/div/div/div/div/div[3]/div[99]</value>
      <webElementGuid>1a9aa69b-55ef-423c-ae11-6ee85949fd20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='India (भारत)'])[1]/following::div[1]</value>
      <webElementGuid>7b6f55a9-e382-4ee2-b408-00b06c21fdc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iceland (Ísland)'])[1]/following::div[5]</value>
      <webElementGuid>841293b2-0e05-4b6d-a402-b931ce4e31fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Iran (‫ایران‬‎)'])[1]/preceding::div[6]</value>
      <webElementGuid>07f590ec-0298-4e8a-9f0e-232c6e113bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[99]</value>
      <webElementGuid>7aaef936-299d-4b0f-9394-ae7e4f546334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' 
          Indonesia
        ' or . = ' 
          Indonesia
        ')]</value>
      <webElementGuid>acb7e65e-bd39-4a9e-b738-3ff0b206ec21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
