<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>newsletter</name>
   <tag></tag>
   <elementGuidId>011d9580-cbcd-49e5-8a6e-af6a81818440</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#register-newsletter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='register-newsletter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c091ad6f-8c20-4a9f-9a5f-81145f79eb3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>register-newsletter</value>
      <webElementGuid>c1bffa3d-06e3-4350-af74-16c7f8b62b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>766d4be8-defc-40e9-89d5-b47cce58afac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>newsletter</value>
      <webElementGuid>4428a7db-f6c4-43cd-b8db-70ce28e49793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>edb01264-bdc9-4f1d-ad8a-e42ccf9ffe68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;register-newsletter&quot;)</value>
      <webElementGuid>8ebf7bda-7f25-476d-a88d-8316c1cada17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='register-newsletter']</value>
      <webElementGuid>a1bb3577-215b-4a89-947c-31c639ac85a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-phone-otp']/div/div/div/div/div/div/span/form/div[4]/label/input</value>
      <webElementGuid>bae2bbce-022a-493a-80b1-a27998e897a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>c0fedd11-29e0-4ac9-a6b6-e55c43d3378e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'register-newsletter' and @type = 'checkbox' and @name = 'newsletter']</value>
      <webElementGuid>11e7c905-9d54-4c6f-876b-a20101f3b734</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
