<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>snk</name>
   <tag></tag>
   <elementGuidId>5e5f1b90-0d7e-4da3-9fcb-55e05a7365cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#termconditions</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='termconditions']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35a699e1-964f-4af1-a8de-b41962deacc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>termconditions</value>
      <webElementGuid>878f925f-d61a-42e3-8ad8-c3471857dd6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>878aedc6-5825-4897-96ab-9a713023618c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>termconditions</value>
      <webElementGuid>1ed76152-9312-40ef-8b2d-3e99914ce52c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input form-check-input</value>
      <webElementGuid>5ddb51ee-95f1-4cc8-a85b-c657a4c25199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;termconditions&quot;)</value>
      <webElementGuid>f70cd65c-5471-49a7-ba46-423cabc1ed37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='termconditions']</value>
      <webElementGuid>1230e181-19ab-464a-900e-2287555d9905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page-phone-otp']/div/div/div/div/div/div/span/form/div[5]/label/input</value>
      <webElementGuid>311baec3-3907-41b9-a7e3-6f5a75983e53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label/input</value>
      <webElementGuid>bd2ffdc5-e3ad-4239-8c17-a00b2effe537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'termconditions' and @type = 'checkbox' and @name = 'termconditions']</value>
      <webElementGuid>c6b1d30e-d6a5-4691-b193-e1f6f3ac45dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
